services:
  - type: web
    name: gds-reader-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gds_server:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
    buildEnv:
      - key: PYTHON_VERSION
        value: "3.11.0"
